### ISSUE TITLE
Image sampling problem

### ISSUE THREAD

**Issue by Losrocks** [Losrocks/Processor#1]
There are two sets of images. The first is the templates held in res/drawable. the second will be pictures taken on a camera.
I need to ensure images are not down sampled so I can print them at a high resolution.

--The images may need to be down sampled in order to accommodate the android heap, if so they would need to be resampled before print

**Comment by uorji3** [comment]
@Losrocks I need some more information. I clone your repo and ran the app on my device. Is the issue about ensuring the image is "good" enough to print? If so, then one needs to know the desired size of the printed image and what would you say is high resolution? 72, 96, 300 dpi? All of these will factor into what formula you need to accept/reject and image once the user has selected one from their device.

**Comment by Losrocks** [comment]
@uorji3  Thank you for taking the time out and helping me with my problem.
I'm taking pictures from various DSLR cameras. One of the main issues i'm concerned with in regards to image size is due to android's limited heap sizes across different devices. 
I've experienced out of memory errors due to having too large of an image size. 
I'm trying to devise a way to achieve three things in preparation for print:
--Present images to clients
--Apply different templates to the image
--Merge the photo and template in full resolution
I'm wondering if the images would have to be down sampled for presentation with changes added in post to full size images in preparation for print.
As for resolution, I'm hoping to print at 300dpi. The largest images I'll be printing is 8x10.
The cameras shouldn't take images larger than 10mb.
I'm looking into using glide at the moment to manage my images. I'm planning on updating my repo sometime today with the glide code. Any thoughts or advice on avoiding out of memory errors will be greatly appreciated
Thank you again for your time.

**Comment by uorji3** [comment]
@Losrocks I've also run into issues in which the dimensions of the image are too large as explained in this [StackOverflow thread](https://stackoverflow.com/questions/15313807/android-maximum-allowed-width-height-of-bitmap).

One simple solution could be to use a thumbnail approach in which you save the image with full resolution on the device and then create a scaled bitmap using the method discussed in this [StackOverflow thread](https://stackoverflow.com/questions/8471226/how-to-resize-image-bitmap-to-a-given-size). You can present this image to client in the UI but eventually use the image with full resolution for print.

I also just ran across this library ([davemorrissey/subsampling-scale-image-view](https://github.com/davemorrissey/subsampling-scale-image-view/tree/master/library)) which claims to work well with large images. I have never used it but it could be worth exploring.

**Comment by Losrocks** [comment]
Solved using SubsampleImageView. Thanks, @uorji3 !
